GET http://localhost:8080/posts

###

GET http://localhost:8080/posts/3

###

POST http://localhost:8080/posts
Content-Type: application/json

{
    "titulo": " A volta dos que não foram",
    "texto": "livro ótimo e sensacional",
    "userId": 2
}

### 
PUT  http://localhost:8080/posts?id=1
Content-Type: application/json

{
    "titulo": " A volta dos que voltaram já",
    "texto": "livro melhor ainda do que a primeira versão"
}

###
DELETE http://localhost:8080/posts?id=2
Content-Type: application/json

