GET http://localhost:8080/usuarios

###

GET http://localhost:8080/usuarios/667290f6-2bf3-400d-98de-0d30858c8716

###

POST http://localhost:8080/usuarios
Content-type: application/json

{
    "email":"laura@gmail.com",
    "senha":"elizabete"
}

###

PUT http://localhost:8080/usuarios?id=fc65abfd-754f-4fb0-ba08-967d463e055a
Content-Type: application/json

{   
    "email":"enzo@gmail.com",
    "senha":"ass"
}

###

DELETE http://localhost:8080/usuarios?id=dd87608f-a068-4963-af64-4de8b6356173
Content-Type: application/json
###



